name: Deploy the Backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone the repo
      Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push the image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: kedar6011/todo-app-backend:${{ github.sha }}

      # # 4Ô∏è‚É£ SSH into VM and deploy the container
      # - name: SSH into VM and deploy container
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.VM_HOST }}
      #     username: ${{ secrets.VM_USER }}
      #     key: ${{ secrets.VM_SSH_KEY }}
      #     script: |
      #       echo "Pulling latest image..."
      #       docker pull kedar6011/todo-app-backend:${{ github.sha }}

      #       echo "Stopping existing container..."
      #       docker stop todo-backend || true
      #       docker rm todo-backend || true

      #       echo "Starting new container..."
      #       docker run -d \
      #         --name todo-backend \
      #         -p 8080:8080 \
      #         -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
      #         kedar6011/todo-app-backend:${{ github.sha }}

      #       echo "Deployment successful üéâ"
